# WAF *facade* levels: pages dressed up to look like they sit behind a real
# commercial WAF/CDN (Cloudflare, AWS WAF, ModSecurity/CRS, Akamai, F5 BIG-IP
# ASM, Imperva Incapsula, …). Each serves a branded block page, ray/incident/
# support IDs, and "protected by" chrome — yet every one is still exploitable,
# because the protection is cosmetic, mis-scoped, or blind to the real sink.
# The lesson in each case is a documented, real-world WAF-evasion class.
require "digest/sha1"

# Shared chrome + helpers for the branded block pages. Kept in a module so the
# top-level route table stays readable and nothing leaks into the global scope.
module WafFacade
  # Cloudflare-style lowercase hex ray id, derived deterministically from the
  # request so the same payload always yields the same id (handy in specs).
  def self.ray_id(seed : String) : String
    Digest::SHA1.hexdigest(seed)[0, 16]
  end

  # F5 ASM support ids look like a long decimal string.
  def self.support_id(seed : String) : String
    digits = Digest::SHA1.hexdigest(seed).chars.select(&.ascii_number?)
    digits.first(18).join.ljust(18, '0')
  end

  # NOTE: `reflected` is inserted RAW on purpose — this block page is the sink.
  def self.cloudflare_block(reflected : String, ray : String) : String
    "<!doctype html><html lang='en'><head><meta charset='utf-8'>
    <title>Attention Required! | Cloudflare</title></head>
    <body style='font-family:-apple-system,BlinkMacSystemFont,Helvetica,Arial,sans-serif;background:#f6f7f8;color:#404040'>
    <div style='max-width:600px;margin:48px auto;padding:24px'>
      <h1>Sorry, you have been blocked</h1>
      <h2>You are unable to access this site</h2>
      <p>This website is using a security service to protect itself from online
      attacks. The action you just performed triggered the security solution.</p>
      <p>Blocked request: #{reflected}</p>
      <hr>
      <p>Cloudflare Ray ID: <strong>#{ray}</strong> &middot; Your IP: 203.0.113.7
      &middot; Performance &amp; security by <strong>Cloudflare</strong></p>
    </div></body></html>"
  end

  def self.aws_block(rid : String) : String
    "<!doctype html><html><head><meta charset='utf-8'><title>403 Forbidden</title></head>
    <body><h1>403 ERROR</h1>
    <h2>The request could not be satisfied.</h2>
    <p>Request blocked. We can't connect to the server for this app or website at
    this time. The request was blocked by <strong>AWS WAF</strong>.</p>
    <p>Generated by cloudfront (CloudFront) Request ID: #{rid}</p>
    </body></html>"
  end

  def self.modsecurity_block(rid : String, score : Int32) : String
    "<!doctype html><html><head><meta charset='utf-8'><title>Not Acceptable!</title></head>
    <body><h1>Not Acceptable!</h1>
    <p>An appropriate representation of the requested resource could not be found
    on this server. This error was generated by <strong>Mod_Security</strong>.</p>
    <p>Inbound anomaly score exceeded (total: #{score}, threshold: 5).</p>
    <p>Support ID: #{rid}</p></body></html>"
  end

  def self.akamai_block(rid : String) : String
    "<!doctype html><html><head><meta charset='utf-8'><title>Access Denied</title></head>
    <body><h1>Access Denied</h1>
    <p>You don't have permission to access the requested URL on this server.</p>
    <p>Reference&nbsp;#18.#{rid[0, 8]}1700#{rid[8, 4]}</p>
    </body></html>"
  end

  def self.f5_block(rid : String) : String
    "<!doctype html><html><head><meta charset='utf-8'><title>Request Rejected</title></head>
    <body><p>The requested URL was rejected. Please consult with your administrator.</p>
    <p>Your support ID is: #{support_id(rid)}</p>
    <p><a href='javascript:history.back()'>[Go Back]</a></p></body></html>"
  end

  def self.incapsula_block(rid : String) : String
    "<!doctype html><html><head><meta charset='utf-8'><title>Request unsuccessful</title></head>
    <body><h2>Request unsuccessful. Incapsula incident ID: 41700#{rid[0, 10]}-#{rid[10, 6]}</h2>
    <p>Powered by <strong>Imperva</strong> &middot; Incapsula.</p></body></html>"
  end

  # OWASP CRS-style anomaly scoring: only the "famous" tokens carry a score, so a
  # payload assembled from low/zero-score primitives stays under the threshold.
  CRS_RULES = {
    /script/i      => 5,
    /onerror/i     => 5,
    /onload/i      => 5,
    /onmouseover/i => 5,
    /onclick/i     => 5,
    /javascript:/i => 4,
    /\balert\b/i   => 3,
    /\beval\b/i    => 3,
    /<\/?\w/       => 1,
  }

  def self.crs_score(input : String) : Int32
    CRS_RULES.sum { |re, pts| input.match(re) ? pts : 0 }
  end
end

# Level 1: Cloudflare-style "Attention Required!" interstitial whose own block
# page reflects the offending request RAW. The WAF *looks* protective — almost
# any scanner payload trips a branded 403 challenge — but the challenge page
# echoes the blocked value without escaping, so the block page is itself the XSS
# sink. The normal page escapes its reflection, so the only way through is the
# block page. Real-world class: WAF/CDN block page reflected XSS.
# Bypass: any blocked payload, e.g. <script>alert(1)</script> or <svg onload=alert(1)>
Xssmaze.push("waf-facade-level1", "/waf-facade/level1/?query=a", "Cloudflare-style block page reflects the blocked payload raw (block-page XSS)",
  vuln: "reflected-html", delivery: ["query"], note: "the normal page HTML-escapes its reflection; the raw reflection is on the branded 403 block page, so the payload has to trip the WAF pattern to reach the sink at all")
maze_get "/waf-facade/level1/" do |env|
  query = env.params.query.fetch("query", "")

  if query.match(/<script|<svg|<img|<iframe|onerror|onload|\bon\w+=|union\s+select|\.\.\//i)
    ray = WafFacade.ray_id(query)
    env.response.status_code = 403
    env.response.headers["Server"] = "cloudflare"
    env.response.headers["CF-RAY"] = "#{ray}-LAX"
    WafFacade.cloudflare_block(query, ray)
  else
    # Non-blocked requests are reflected SAFELY — the block page is the only sink.
    "<!doctype html><html><head><meta charset='utf-8'><title>Search</title></head><body>
    <h1>Search</h1>
    <p>Results for: #{Xssmaze.html_escape(query)}</p>
    </body></html>"
  end
end

# Level 2: AWS WAF-style "Request blocked" page. The rule engine only inspects a
# fixed-size window at the start of the value (modeling AWS WAF's body/inspection
# size limit), then reflects the full value raw. A long benign prefix pushes the
# real payload past the inspection window.
# Bypass: 100+ chars of padding, then the vector —
#   ?query=aaaa…(100)…aaaa<svg onload=alert(1)>
Xssmaze.push("waf-facade-level2", "/waf-facade/level2/?query=a", "AWS WAF-style inspection-size cap: only the first 100 bytes are scanned",
  vuln: "reflected-html", delivery: ["query"], note: "only the first 100 bytes are inspected, so padding the value past that window gets the full string reflected raw")
maze_get "/waf-facade/level2/" do |env|
  query = env.params.query.fetch("query", "")
  window = query[0, 100]

  if window.match(/<|>|script|\bon\w+=/i)
    env.response.status_code = 403
    WafFacade.aws_block(WafFacade.ray_id(query))
  else
    "<!doctype html><html><head><meta charset='utf-8'><title>Catalog</title></head><body>
    <h1>Product Catalog</h1>
    <div class='results'>#{query}</div>
    </body></html>"
  end
end

# Level 3: ModSecurity / OWASP CRS-style anomaly scoring. Each matched signature
# adds to a running score; the request is blocked only when the total crosses the
# inbound threshold (5). The rule set only scores the famous tokens, so a payload
# built from un-scored primitives slips under.
# Bypass: avoid the scored keywords, e.g.
#   <input autofocus onfocus=confirm(1)>   (input/onfocus/confirm are un-scored)
Xssmaze.push("waf-facade-level3", "/waf-facade/level3/?query=a", "ModSecurity CRS-style anomaly scoring (un-scored primitives slip under the threshold)",
  vuln: "reflected-html", delivery: ["query"], note: "anomaly scoring blocks at 5 points, so a payload built from un-scored primitives such as <input autofocus onfocus=confirm(1)> stays under the threshold")
maze_get "/waf-facade/level3/" do |env|
  query = env.params.query.fetch("query", "")
  score = WafFacade.crs_score(query)

  if score >= 5
    env.response.status_code = 406
    WafFacade.modsecurity_block(WafFacade.ray_id(query), score)
  else
    "<!doctype html><html><head><meta charset='utf-8'><title>Feedback</title></head><body>
    <h1>Customer Feedback</h1>
    <div class='comment'>#{query}</div>
    </body></html>"
  end
end

# Level 4: Akamai-style "Access Denied" facade. The WAF inspects the query
# parameter and serves a branded reference-ID block page for tag/event payloads —
# but the page ALSO reflects the User-Agent header raw, and the WAF never looks at
# it. Classic scope gap: the WAF guards query/body, a header sink is missed.
# Bypass: keep ?query benign, put the payload in the User-Agent header —
#   User-Agent: <img src=x onerror=alert(1)>
Xssmaze.push("waf-facade-level4", "/waf-facade/level4/?query=a", "Akamai-style WAF guards the query but reflects the User-Agent header raw", "GET", ["query", "User-Agent"],
  vuln: "reflected-html", delivery: ["header"], note: "the query parameter is escaped and guarded, but the User-Agent header is reflected raw and never inspected, so the payload goes in the header while query stays benign")
maze_get "/waf-facade/level4/" do |env|
  query = env.params.query.fetch("query", "")
  ua = env.request.headers["User-Agent"]? || "unknown"

  if query.match(/<|>|\bon\w+=|script/i)
    env.response.status_code = 403
    WafFacade.akamai_block(WafFacade.ray_id(query))
  else
    # Query is escaped; the unguarded User-Agent header is the real sink.
    "<!doctype html><html><head><meta charset='utf-8'><title>Account</title></head><body>
    <h1>Account Overview</h1>
    <p>Search: #{Xssmaze.html_escape(query)}</p>
    <p class='client'>Signed in from: #{ua}</p>
    </body></html>"
  end
end

# Level 5: F5 BIG-IP ASM-style rejection. Serves the unmistakable ASM block page
# ("The requested URL was rejected… Your support ID is: …") but the signature set
# is a case-SENSITIVE literal denylist, so a case-folded vector walks straight
# past it before being reflected raw.
# Bypass: case-fold the tag/handler, e.g.  <SvG OnLoad=alert(1)>  or  <ScRiPt>alert(1)</ScRiPt>
Xssmaze.push("waf-facade-level5", "/waf-facade/level5/?query=a", "F5 ASM-style case-sensitive literal denylist (case-fold bypass)",
  vuln: "reflected-html", delivery: ["query"], note: "the denylist is case-sensitive, so a case-folded vector such as <SvG OnLoad=...> walks straight past it")
maze_get "/waf-facade/level5/" do |env|
  query = env.params.query.fetch("query", "")

  # Case-sensitive literal denylist (no /i): only the lowercase forms are caught.
  blocked = query.includes?("<script>") || query.includes?("</script>") ||
            query.includes?("onerror=") || query.includes?("onload=") ||
            query.includes?("<svg") || query.includes?("<img")

  if blocked
    env.response.status_code = 403
    WafFacade.f5_block(WafFacade.ray_id(query))
  else
    "<!doctype html><html><head><meta charset='utf-8'><title>Portal</title></head><body>
    <h1>Customer Portal</h1>
    <div class='msg'>#{query}</div>
    </body></html>"
  end
end

# Level 6: Imperva/Incapsula-style "Request unsuccessful. Incapsula incident ID…"
# facade. The rule set is tuned for HTML tag injection — any opening tag trips the
# branded block page — but the reflection actually lands inside a single-quoted JS
# string, where no angle brackets are needed at all.
# Bypass: break the JS string instead of injecting a tag —  ';alert(1)//
Xssmaze.push("waf-facade-level6", "/waf-facade/level6/?query=a", "Incapsula-style tag-focused WAF, but the reflection is in a JS string context",
  vuln: "reflected-js", delivery: ["query"], note: "any opening tag trips the block page, but the reflection is in a single-quoted JS string where no angle brackets are needed")
maze_get "/waf-facade/level6/" do |env|
  query = env.params.query.fetch("query", "")

  if query.match(/<[a-z!\/]/i)
    env.response.status_code = 403
    WafFacade.incapsula_block(WafFacade.ray_id(query))
  else
    "<!doctype html><html><head><meta charset='utf-8'><title>Greeting</title></head><body>
    <h1>Welcome back</h1>
    <div id='out'></div>
    <script>
      var user = '#{query}';
      document.getElementById('out').textContent = 'Hello, ' + user;
    </script>
    </body></html>"
  end
end

# Level 7: "Protected by ShieldWall WAF" — except the WAF is pure client-side
# theater. A JS routine sanitizes the URL param and writes a *safe* echo, giving
# the page a protected look, but the server already reflected the raw parameter
# into the DOM before any script runs. The server response is the real sink.
# Bypass: just send the payload — it is already in the initial HTML —
#   ?query=<img src=x onerror=alert(1)>
Xssmaze.push("waf-facade-level7", "/waf-facade/level7/?query=a", "Cosmetic client-side WAF: the server reflects raw before the JS 'sanitizer' runs",
  vuln: "reflected-html", delivery: ["query"], note: "the client-side sanitizer only feeds a second element; the server already reflected the raw value into #preview before any script ran")
maze_get "/waf-facade/level7/" do |env|
  query = env.params.query.fetch("query", "")

  "<!doctype html><html><head><meta charset='utf-8'><title>ShieldWall Protected</title></head><body>
  <div class='banner'>[Protected] This site is protected by ShieldWall WAF v4.2</div>
  <h1>Comment Preview</h1>
  <!-- Server-rendered preview (raw, before any JS runs) -->
  <div id='preview'>#{query}</div>
  <div id='safe'></div>
  <script>
    // Client-side 'WAF': strips tags from the URL param before showing it.
    // Purely cosmetic — the #preview div above already holds the raw value.
    function shieldwall(s){ return s.replace(/<[^>]*>/g, ''); }
    var raw = new URLSearchParams(location.search).get('query') || '';
    document.getElementById('safe').textContent = 'Filtered: ' + shieldwall(raw);
  </script>
  </body></html>"
end

# Level 8: Cloudflare-style "Checking your browser before you access…" JS
# challenge interstitial. The page looks like a DDoS/bot challenge, but once the
# fake check finishes it reads ?query from the URL and writes it via innerHTML —
# the challenge screen is the DOM-XSS sink. Pure client-side, no server reflection.
# Bypass: ?query=<img src=x onerror=alert(1)>
Xssmaze.push("waf-facade-level8", "/waf-facade/level8/?query=a", "Cloudflare-style JS challenge interstitial whose 'verify' step is a DOM innerHTML sink",
  vuln: "dom", sources: ["location.search"], sinks: ["innerHTML"], delivery: ["query"], note: "the server response ignores the parameter entirely; the sink runs in a setTimeout about 600 ms after load")
maze_get "/waf-facade/level8/" do |_env|
  "<!doctype html><html><head><meta charset='utf-8'>
  <title>Just a moment...</title></head><body>
  <h1>Checking your browser before accessing the site.</h1>
  <p id='cf-spinner'>This process is automatic. Your browser will redirect shortly.</p>
  <p>DDoS protection by <strong>Cloudflare</strong></p>
  <div id='challenge-output'></div>
  <script>
    // Fake challenge: 'verifies' the visitor, then renders the requested resource.
    setTimeout(function(){
      var q = new URLSearchParams(location.search).get('query') || '';
      document.getElementById('challenge-output').innerHTML =
        'Access granted. Requested resource: ' + q;
    }, 600);
  </script>
  </body></html>"
end
